/// <reference path="../typings/global.d.ts" />
// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../../@micro-app/types

declare module '@micro-zoe/micro-app' {
    export { default, MicroApp, getActiveApps, getAllApps, unmountApp, unmountAllApps, } from '@micro-zoe/micro-app/micro_app';
    export { default as preFetch, } from '@micro-zoe/micro-app/prefetch';
    export { removeDomScope, pureCreateElement, version, } from '@micro-zoe/micro-app/libs/utils';
    export { EventCenterForMicroApp, } from '@micro-zoe/micro-app/interact';
}

declare module '@micro-zoe/micro-app/micro_app' {
    import type { OptionsType, MicroAppConfigType, lifeCyclesType, plugins, fetchType } from '@micro-app/types';
    import preFetch from '@micro-zoe/micro-app/prefetch';
    import { EventCenterForBaseApp } from '@micro-zoe/micro-app/interact';
    /**
        * if app not prefetch & not unmount, then app is active
        * @param excludeHiddenApp exclude hidden keep-alive app, default is false
        * @returns active apps
        */
    export function getActiveApps(excludeHiddenApp?: boolean): string[];
    export function getAllApps(): string[];
    export interface unmountAppParams {
            destroy?: boolean;
            clearAliveState?: boolean;
    }
    /**
        * unmount app by appName
        * @param appName
        * @param options unmountAppParams
        * @returns Promise<void>
        */
    export function unmountApp(appName: string, options?: unmountAppParams): Promise<void>;
    export function unmountAllApps(options?: unmountAppParams): Promise<void>;
    export class MicroApp extends EventCenterForBaseApp implements MicroAppConfigType {
            tagName: string;
            shadowDOM?: boolean;
            destroy?: boolean;
            inline?: boolean;
            disableScopecss?: boolean;
            disableSandbox?: boolean;
            ssr?: boolean;
            lifeCycles?: lifeCyclesType;
            plugins?: plugins;
            fetch?: fetchType;
            preFetch: typeof preFetch;
            excludeAssetFilter?: (assetUrl: string) => boolean;
            start(options?: OptionsType): void;
    }
    const _default: MicroApp;
    export default _default;
}

declare module '@micro-zoe/micro-app/prefetch' {
    import type { prefetchParamList, globalAssetsType } from '@micro-app/types';
    /**
        * preFetch([
        *  {
        *    name: string,
        *    url: string,
        *    disableScopecss?: boolean,
        *    disableSandbox?: boolean,
        *  },
        *  ...
        * ])
        * Note:
        *  1: preFetch is asynchronous and is performed only when the browser is idle
        *  2: disableScopecss, disableSandbox must be same with micro-app element, if conflict, the one who executes first shall prevail
        * @param apps micro apps
        */
    export default function preFetch(apps: prefetchParamList): void;
    /**
        * load global assets into cache
        * @param assets global assets of js, css
        */
    export function getGlobalAssets(assets: globalAssetsType): void;
}

declare module '@micro-zoe/micro-app/libs/utils' {
    import type { Func } from '@micro-app/types';
    export const version = "__MICRO_APP_VERSION__";
    export const isBrowser: boolean;
    export const globalThis: any;
    export function isUndefined(target: unknown): target is undefined;
    export function isNull(target: unknown): target is null;
    export function isString(target: unknown): target is string;
    export function isBoolean(target: unknown): target is boolean;
    export function isFunction(target: unknown): boolean;
    export const isArray: (arg: any) => arg is any[];
    export function isPlainObject(target: unknown): boolean;
    export function isPromise(target: unknown): boolean;
    export function isBoundFunction(target: any): boolean;
    export function isShadowRoot(target: unknown): boolean;
    export const rawDefineProperty: (o: any, p: string | number | symbol, attributes: PropertyDescriptor & ThisType<any>) => any;
    export const rawDefineProperties: (o: any, properties: PropertyDescriptorMap & ThisType<any>) => any;
    export const rawHasOwnProperty: (v: string | number | symbol) => boolean;
    /**
        * format error log
        * @param msg message
        * @param appName app name, default is null
        */
    export function logError(msg: unknown, appName?: string | null, ...rest: any[]): void;
    /**
        * format warn log
        * @param msg message
        * @param appName app name, default is null
        */
    export function logWarn(msg: unknown, appName?: string | null, ...rest: any[]): void;
    /**
        * async execution
        * @param fn callback
        * @param args params
        */
    export function defer(fn: Func, ...args: any[]): void;
    /**
        * Add address protocol
        * @param url address
        */
    export function addProtocol(url: string): string;
    /**
        * format URL address
        * note the scenes:
        * 1. micro-app -> attributeChangedCallback
        * 2. preFetch
        */
    export function formatAppURL(url: string | null, appName?: string | null): string;
    /**
        * format name
        * note the scenes:
        * 1. micro-app -> attributeChangedCallback
        * 2. event_center -> EventCenterForMicroApp -> constructor
        * 3. event_center -> EventCenterForBaseApp -> all methods
        * 4. preFetch
        * 5. plugins
        */
    export function formatAppName(name: string | null): string;
    /**
        * Get valid address, such as https://xxx/xx/xx.html to https://xxx/xx/
        * @param url app.url
        */
    export function getEffectivePath(url: string): string;
    /**
        * Complete address
        * @param path address
        * @param baseURI base url(app.url)
        */
    export function CompletionPath(path: string, baseURI: string): string;
    /**
        * Get the folder where the link resource is located,
        * which is used to complete the relative address in the css
        * @param linkPath full link address
        */
    export function getLinkFileDir(linkPath: string): string;
    /**
        * promise stream
        * @param promiseList promise list
        * @param successCb success callback
        * @param errorCb failed callback
        * @param finallyCb finally callback
        */
    export function promiseStream<T>(promiseList: Array<Promise<T> | T>, successCb: CallableFunction, errorCb: CallableFunction, finallyCb?: CallableFunction): void;
    export function isSupportModuleScript(): boolean;
    export function createNonceSrc(): string;
    export function unique(array: any[]): any[];
    export const requestIdleCallback: any;
    export function setCurrentAppName(appName: string | null): void;
    export function throttleDeferForSetAppName(appName: string): void;
    export function getCurrentAppName(): string | null;
    export function removeDomScope(): void;
    export function isSafari(): boolean;
    /**
        * Create pure elements
        */
    export function pureCreateElement<K extends keyof HTMLElementTagNameMap>(tagName: K, options?: ElementCreationOptions): HTMLElementTagNameMap[K];
    /**
        * clone origin elements to target
        * @param origin Cloned element
        * @param target Accept cloned elements
        * @param deep deep clone or transfer dom
        */
    export function cloneContainer<T extends Element, Q extends Element>(origin: T, target: Q, deep: boolean): void;
    export function isInvalidQuerySelectorKey(key: string): boolean;
    export function isUniqueElement(key: string): boolean;
    /**
        * get micro-app element
        * @param target app container
        */
    export function getRootContainer(target: HTMLElement | ShadowRoot): HTMLElement;
    /**
        * trim start & end
        */
    export function trim(str: string): string;
    export function isFireFox(): boolean;
}

declare module '@micro-zoe/micro-app/interact' {
    import { CallableFunctionForInteract } from '@micro-app/types';
    class EventCenterForGlobal {
            /**
                * add listener of global data
                * @param cb listener
                * @param autoTrigger If there is cached data when first bind listener, whether it needs to trigger, default is false
                */
            addGlobalDataListener(cb: CallableFunctionForInteract, autoTrigger?: boolean): void;
            /**
                * remove listener of global data
                * @param cb listener
                */
            removeGlobalDataListener(cb: CallableFunctionForInteract): void;
            /**
                * dispatch global data
                * @param data data
                */
            setGlobalData(data: Record<PropertyKey, unknown>): void;
            /**
                * get global data
                */
            getGlobalData(): Record<PropertyKey, unknown> | null;
            /**
                * clear all listener of global data
                * if appName exists, only the specified functions is cleared
                * if appName not exists, only clear the base app functions
                */
            clearGlobalDataListener(): void;
    }
    export class EventCenterForBaseApp extends EventCenterForGlobal {
            /**
                * add listener
                * @param appName app.name
                * @param cb listener
                * @param autoTrigger If there is cached data when first bind listener, whether it needs to trigger, default is false
                */
            addDataListener(appName: string, cb: CallableFunction, autoTrigger?: boolean): void;
            /**
                * remove listener
                * @param appName app.name
                * @param cb listener
                */
            removeDataListener(appName: string, cb: CallableFunction): void;
            /**
                * get data from micro app or base app
                * @param appName app.name
                * @param fromBaseApp whether get data from base app, default is false
                */
            getData(appName: string, fromBaseApp?: boolean): Record<PropertyKey, unknown> | null;
            /**
                * Dispatch data to the specified micro app
                * @param appName app.name
                * @param data data
                */
            setData(appName: string, data: Record<PropertyKey, unknown>): void;
            /**
                * clear all listener for specified micro app
                * @param appName app.name
                */
            clearDataListener(appName: string): void;
    }
    export class EventCenterForMicroApp extends EventCenterForGlobal {
            appName: string;
            umdDataListeners?: {
                    global: Set<CallableFunctionForInteract>;
                    normal: Set<CallableFunctionForInteract>;
            };
            constructor(appName: string);
            /**
                * add listener, monitor the data sent by the base app
                * @param cb listener
                * @param autoTrigger If there is cached data when first bind listener, whether it needs to trigger, default is false
                */
            addDataListener(cb: CallableFunctionForInteract, autoTrigger?: boolean): void;
            /**
                * remove listener
                * @param cb listener
                */
            removeDataListener(cb: CallableFunctionForInteract): void;
            /**
                * get data from base app
                */
            getData(): Record<PropertyKey, unknown> | null;
            /**
                * dispatch data to base app
                * @param data data
                */
            dispatch(data: Record<PropertyKey, unknown>): void;
            /**
                * clear all listeners
                */
            clearDataListener(): void;
    }
    /**
        * Record UMD function before exec umdHookMount
        * @param microAppEventCenter
        */
    export function recordDataCenterSnapshot(microAppEventCenter: EventCenterForMicroApp): void;
    /**
        * Rebind the UMD function of the record before remount
        * @param microAppEventCenter instance of EventCenterForMicroApp
        */
    export function rebuildDataCenterSnapshot(microAppEventCenter: EventCenterForMicroApp): void;
    export {};
}

